Algoritmo "semnome"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/09/2025
Var
// Seção de Declarações das variáveis 
i, conta:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i <- 15
 repita
 conta <- i * i
 escreval(conta)
 i <- i+1
 ate i > 200

Fimalgoritmo