Algoritmo "semnome"
// Disciplina    Lógica de Programação
// Professor   : Jailson Costa dos Santos 
// Descrição   : calcula o quadrado da diferença
// Autor(a)    : Eduardo Barbosa Silva
// Data atual  : 18/09/2025
Var
// Seção de Declarações das variáveis 
a,b:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite o valor x e y")
leia(a,b)
a <- a-b
a <- a*a
escreval("o quadrado da diferença é: ",a)

Fimalgoritmo