Algoritmo "par_ou_impar"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Descobre se um número é impar ou par
// Autor(a)    : Eduardo Barbosa Silva
// Data atual  : 19/09/2025
Var
// Seção de Declarações das variáveis 
a:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número inteiro: ")
leia(a)
se (a % 2 = 0) entao
escreval("Número par")
senao
escreval("Número impar")
fimse

Fimalgoritmo