Algoritmo "taboada"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Realiza a taboada
// Autor(a)    : Eduardo Barbosa Silva
// Data atual  : 15/09/2025
Var
// Seção de Declarações das variáveis 
tabela, i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite um valor")
leia(tabela)
i <- 1
enquanto i <= 10 faca
escreval(tabela," x ",i," = ",i*tabela)
i <- i+1
fimenquanto

Fimalgoritmo