Algoritmo "impar20"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Demonstra todos os números impares de 0 a 20
// Autor(a)    : Eduardo Barbosa Silva
// Data atual  : 15/09/2025
Var
   // Seção de Declarações das variáveis
   i:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   i<-0
   enquanto i < 20 faca
      se i % 2 <> 0 entao
         escreva(i)
      fimse
      i <- i+1
   fimenquanto

Fimalgoritmo