Algoritmo "ceminteiro"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Programa que exibe a soma de cem primeiros números inteiros
// Autor(a)    : Eduardo Barbosa Silva
// Data atual  : 20/09/2025
Var
   soma, i: inteiro
Inicio
   soma <- 0
   para i de 1 ate 100 faca
      soma <- soma + i
   fimpara
   escreval("A soma dos 100 primeiros números inteiros é: ", soma)
Fimalgoritmo