Algoritmo "imparde1a20"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Programa que revela os valores numéricos impares dentro de 1 a 20
// Autor(a)    : Eduardo Barbosa Silva
// Data atual  : 20/09/2025
var
   numero: inteiro
inicio
   escreval("Números ímpares de 0 a 20:")
   para numero de 0 ate 20 faca
      se (numero % 2 <> 0) entao
         escreval(numero)
      fimse
   fimpara
fimalgoritmo